version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "ready-for-review"
    assignees:
      - "mesosphere/kommander"
    reviewers:
      - "mesosphere/kommander"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mesosphere/kommander"
