run:
  go: '1.17'

linters:
  disable-all: true
  enable:
    - containedctx
    - contextcheck
    - depguard
    - errcheck
    - errchkjson
    - errname
    - gochecknoinits
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/mesosphere)
      - Prefix(github.com/mesosphere/daggers-for-dkp)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  revive:
    max-open-files: 2048
    severity: error
    rules:
      - name: cognitive-complexity
        arguments: [7]
      - name: cyclomatic
        arguments: [10]
      - name: exported
      - name: function-result-limit
        arguments: [3]
      - name: line-length-limit
        arguments: [120]

issues:
  include:
    - EXC0012
    - EXC0014
  exclude-rules:
    # ignore errcheck for code under a /test folder
    - path: "test/*"
      linters:
        - errcheck
    # ignore errcheck for flags.Parse (it is expected that we flag.ExitOnError)
    # ignore response.WriteError as it always returns the err it was passed
    - source: "flags.Parse|response.WriteError"
      linters:
        - errcheck
