name: code-quality-pr-size-label

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: size-label
        uses: pascalgn/size-label-action@bbbaa0d5ccce8e2e76254560df5c64b82dac2e12 # v0.5.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
