name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: mfinelli/setup-shfmt@v2
        with:
          shfmt-version: ${{ fromJson(steps.versions.outputs.tools).shfmt }}

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --show-diff-on-failure
        env:
          SKIP: no-commit-to-branch,golangci-lint
